import { describe, it, expect } from "vitest";
import { runAiPatternChecks, detectAiTools } from "./checks-ai";
import { buildTestProject } from "./test-utils";

describe("checks-ai · AI-pattern detection", () => {
  it("flags empty catch block", () => {
    const issues = runAiPatternChecks(
      buildTestProject([
        {
          path: "lib/x.ts",
          content: `try { JSON.parse("{}"); } catch {}`,
        },
      ]),
    );
    expect(issues.some((i) => i.checkId === "ai_pattern/silent-catch")).toBe(
      true,
    );
  });

  it("flags catch with only a return statement", () => {
    const issues = runAiPatternChecks(
      buildTestProject([
        {
          path: "lib/x.ts",
          content: `function f() { try { return doSomething(); } catch { return null; } }`,
        },
      ]),
    );
    expect(issues.some((i) => i.checkId === "ai_pattern/silent-catch")).toBe(
      true,
    );
  });

  it("flags placeholder page", () => {
    const issues = runAiPatternChecks(
      buildTestProject([
        {
          path: "app/dashboard/page.tsx",
          content: `export default function Page() { return <div>TODO: build this</div>; }`,
        },
      ]),
    );
    expect(
      issues.some((i) => i.checkId === "ai_pattern/placeholder-page"),
    ).toBe(true);
  });

  it("flags stub API route", () => {
    const issues = runAiPatternChecks(
      buildTestProject([
        {
          path: "app/api/x/route.ts",
          content: `import { NextResponse } from 'next/server';\nexport async function GET() { return NextResponse.json({ ok: true }); }`,
        },
      ]),
    );
    expect(issues.some((i) => i.checkId === "ai_pattern/stub-route")).toBe(
      true,
    );
  });

  it("flags FIXME/HACK comments", () => {
    const issues = runAiPatternChecks(
      buildTestProject([
        {
          path: "lib/x.ts",
          content: `// FIXME: rotate this key\nconst k = "x";`,
        },
      ]),
    );
    expect(issues.some((i) => i.checkId === "ai_pattern/temp-comment")).toBe(
      true,
    );
  });

  it("flags console.log in non-test files", () => {
    const issues = runAiPatternChecks(
      buildTestProject([
        {
          path: "lib/x.ts",
          content: `function f() { console.log("debug"); return 1; }`,
        },
      ]),
    );
    expect(issues.some((i) => i.checkId === "ai_pattern/console-log")).toBe(
      true,
    );
  });

  it("detects Next.js + React from page artifacts", () => {
    const tools = detectAiTools(
      buildTestProject([
        {
          path: ".cursor/rules.md",
          content: "edit rules",
        },
      ]),
    );
    expect(tools).toContain("cursor");
  });

  it("detects v0 from inline marker", () => {
    const tools = detectAiTools(
      buildTestProject([
        {
          path: "app/foo.tsx",
          content: `// generated by v0.dev\nexport const x = 1;`,
        },
      ]),
    );
    expect(tools).toContain("v0");
  });
});
