/**
 * GET /api/test-gen/[issueId]
 * Returns a Vitest-style regression test for the issue, generated by Claude.
 */
import { NextResponse, type NextRequest } from "next/server";
import { getSupabaseServer } from "@/lib/supabase-server";
import { getSupabaseAdmin } from "@/lib/supabase-admin";
import { getOrGenerateTest } from "@/lib/test-gen";

export const runtime = "nodejs";
export const maxDuration = 30;

export async function GET(
  _req: NextRequest,
  ctx: { params: Promise<{ issueId: string }> },
) {
  const { issueId } = await ctx.params;
  const supabase = await getSupabaseServer();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return new NextResponse("unauthorised", { status: 401 });

  const admin = getSupabaseAdmin();
  const { data: issue } = await admin
    .from("issues")
    .select(
      "id, title, description, severity, dimension, file_path, line_number, code_snippet",
    )
    .eq("id", issueId)
    .single();
  if (!issue) {
    return NextResponse.json(
      { ok: false, error: "issue-not-found" },
      { status: 404 },
    );
  }
  type IssueRow = {
    id: string;
    title: string;
    description: string | null;
    severity: string;
    dimension: string;
    file_path: string;
    line_number: number | null;
    code_snippet: string | null;
  };
  const i = issue as IssueRow;

  const result = await getOrGenerateTest({
    issueId: i.id,
    title: i.title,
    description: i.description ?? "",
    filePath: i.file_path,
    lineNumber: i.line_number ?? undefined,
    codeSnippet: i.code_snippet ?? undefined,
    severity: i.severity,
    dimension: i.dimension,
  });

  return NextResponse.json({
    ok: true,
    issueId: i.id,
    test: result.test,
    cached: result.cached,
    generated: result.generated,
  });
}
